---
galaxy_info:
  author: 'Simon Baerlocher (https://sbaerlocher.ch)'
  description: 'This role installs Hashicorps Packer on Windows and Linux'
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Windows
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - hashicorps
    - packer
    - windows
    - linux

dependencies: []
