---
# tasks file for vagrant

- name: 'Find all versions of Vagrant'
  uri:
    url: https://releases.hashicorp.com/vagrant/index.json
    return_content: true
  register: vagrant_index

- name: 'Finds the latest version of Vagrant when latest var is define'
  set_fact:
    current_version: '{{ item }}'
  with_items: '{{ (vagrant_index.content | from_json).versions | list | sort | last }}'

- name: include distribution tasks
  include_tasks: '{{ loop_distribution }}'
  with_first_found:
    - files:
        - '{{ distribution }}-{{ distribution_verion }}.yml'
        - '{{ distribution }}-{{ distribution_major_version }}.yml'
        - '{{ distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - '{{ ansible_system }}.yml'
        - 'defaults.yml'
      paths:
        - 'distribution'
  loop_control:
    loop_var: loop_distribution
  vars:
    distribution: '{{ ansible_distribution }}'
    distribution_verion: '{{ ansible_distribution_version }}'
    distribution_major_version: '{{ ansible_distribution_major_version }}'
